"""Fixed control definitions for the local risk / compliance evaluator."""

from __future__ import annotations

from governance_platform.compliance.entities import ControlDefinition
from governance_platform.compliance.enums import (
    ComplianceEntityType,
    ControlDomain,
    ControlSeverity,
)


def default_control_definitions() -> tuple[ControlDefinition, ...]:
    """Return the deterministic, restrained Milestone 5 control set."""
    return (
        ControlDefinition(
            control_id="CTRL-0001",
            name="Inventory identifiers are unique",
            description="Dataset, model, and research project identifiers must not be duplicated.",
            control_domain=ControlDomain.INVENTORY_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.PORTFOLIO,),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0002",
            name="Inventory references resolve",
            description="Model and research-project dataset/model references must resolve.",
            control_domain=ControlDomain.INVENTORY_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.PORTFOLIO,),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0003",
            name="Synthetic-data-only invariant holds",
            description="Every dataset remains explicitly marked as synthetic only.",
            control_domain=ControlDomain.INVENTORY_GOVERNANCE,
            severity=ControlSeverity.CRITICAL,
            applies_to=(ComplianceEntityType.DATASET,),
            evidence_requirements=("dataset_registration", "adr_0001"),
        ),
        ControlDefinition(
            control_id="CTRL-0004",
            name="Ownership and stewardship metadata is present",
            description="Datasets and models must carry owner/steward metadata as applicable.",
            control_domain=ControlDomain.INVENTORY_GOVERNANCE,
            severity=ControlSeverity.MEDIUM,
            applies_to=(ComplianceEntityType.DATASET, ComplianceEntityType.MODEL),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0005",
            name="Review dates are recorded for approved active inventory",
            description="Approved active datasets and models should have a recorded review date.",
            control_domain=ControlDomain.OPERATIONAL_GOVERNANCE,
            severity=ControlSeverity.LOW,
            applies_to=(ComplianceEntityType.DATASET, ComplianceEntityType.MODEL),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0006",
            name="Research-prohibited datasets are not actively granted",
            description=(
                "Datasets with research_use_allowed=false must not appear in active grants."
            ),
            control_domain=ControlDomain.DATASET_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0007",
            name="Granted datasets are approved",
            description="Datasets in active grants must be in approved governance state.",
            control_domain=ControlDomain.DATASET_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0008",
            name="Dataset sensitivity classification is present",
            description="Every dataset must carry a sensitivity classification.",
            control_domain=ControlDomain.DATASET_GOVERNANCE,
            severity=ControlSeverity.MEDIUM,
            applies_to=(ComplianceEntityType.DATASET,),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0009",
            name="Granted dataset lifecycle is compatible with use",
            description="Datasets in active grants must be in active lifecycle state.",
            control_domain=ControlDomain.DATASET_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0010",
            name="Approved high-risk models have approved responsible-AI review",
            description=(
                "Approved high-risk models must have approved responsible-AI review status."
            ),
            control_domain=ControlDomain.MODEL_GOVERNANCE,
            severity=ControlSeverity.CRITICAL,
            applies_to=(ComplianceEntityType.MODEL,),
            evidence_requirements=("inventory_portfolio", "responsible_ai_review_status"),
        ),
        ControlDefinition(
            control_id="CTRL-0011",
            name="Approved high-risk models require monitoring",
            description="Approved high-risk models must have monitoring_required=true.",
            control_domain=ControlDomain.MODEL_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.MODEL,),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0012",
            name="Granted models are approved",
            description="Models in active grants must be in approved governance state.",
            control_domain=ControlDomain.MODEL_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0013",
            name="Model linked datasets resolve",
            description="Every model linked_dataset_id must resolve to a dataset.",
            control_domain=ControlDomain.MODEL_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.MODEL,),
            evidence_requirements=("inventory_portfolio",),
        ),
        ControlDefinition(
            control_id="CTRL-0014",
            name="High-risk model readiness is tracked",
            description="Non-approved high-risk models should not be treated as ready for use.",
            control_domain=ControlDomain.RESPONSIBLE_AI_READINESS,
            severity=ControlSeverity.MEDIUM,
            applies_to=(ComplianceEntityType.MODEL,),
            evidence_requirements=("inventory_portfolio", "responsible_ai_review_status"),
        ),
        ControlDefinition(
            control_id="CTRL-0015",
            name="Active grants reference approved projects",
            description="Every active grant must reference an approved research project.",
            control_domain=ControlDomain.RESEARCH_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0016",
            name="Active grant projects are not expired at evaluation time",
            description="Every active grant's project must remain unexpired at evaluation time.",
            control_domain=ControlDomain.RESEARCH_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0017",
            name="Granted assets are within project scope",
            description=(
                "Granted datasets and models must be listed on the grant's research project."
            ),
            control_domain=ControlDomain.RESEARCH_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0018",
            name="Grants have approved decision evidence",
            description="Every grant must trace to an approved decision and grant-created event.",
            control_domain=ControlDomain.ACCESS_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("access_control_state", "audit_events"),
        ),
        ControlDefinition(
            control_id="CTRL-0019",
            name="Rejected requests do not produce grants",
            description="Rejected access requests must have no access grants.",
            control_domain=ControlDomain.ACCESS_GOVERNANCE,
            severity=ControlSeverity.CRITICAL,
            applies_to=(ComplianceEntityType.ACCESS_REQUEST,),
            evidence_requirements=("access_control_state",),
        ),
        ControlDefinition(
            control_id="CTRL-0020",
            name="Grants are time-bounded",
            description="Every grant must have an expiry later than its grant timestamp.",
            control_domain=ControlDomain.ACCESS_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("access_control_state",),
        ),
        ControlDefinition(
            control_id="CTRL-0021",
            name="Revoked or expired grants are not active",
            description="Revoked and time-expired grants must not evaluate as active.",
            control_domain=ControlDomain.ACCESS_GOVERNANCE,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.ACCESS_GRANT,),
            evidence_requirements=("access_control_state",),
        ),
        ControlDefinition(
            control_id="CTRL-0022",
            name="Audit completeness passes",
            description="The audit completeness checker must report no missing expected evidence.",
            control_domain=ControlDomain.AUDIT_COMPLETENESS,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.AUDIT_LOG,),
            evidence_requirements=("audit_events", "inventory_portfolio", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0023",
            name="Required lifecycle events exist",
            description=(
                "Requests, decisions, grants, revocations, and expiries need lifecycle events."
            ),
            control_domain=ControlDomain.AUDIT_COMPLETENESS,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.AUDIT_LOG,),
            evidence_requirements=("audit_events", "access_control_state"),
        ),
        ControlDefinition(
            control_id="CTRL-0024",
            name="Correlation chains are traceable",
            description="Each request must have a traceable audit correlation group.",
            control_domain=ControlDomain.AUDIT_COMPLETENESS,
            severity=ControlSeverity.MEDIUM,
            applies_to=(ComplianceEntityType.ACCESS_REQUEST,),
            evidence_requirements=("audit_events",),
        ),
        ControlDefinition(
            control_id="CTRL-0025",
            name="Duplicate audit IDs are absent",
            description="Audit event identifiers must be unique.",
            control_domain=ControlDomain.AUDIT_COMPLETENESS,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.AUDIT_LOG,),
            evidence_requirements=("audit_events",),
        ),
        ControlDefinition(
            control_id="CTRL-0026",
            name="Compliance evidence references resolve",
            description="Every compliance finding evidence reference must resolve in source state.",
            control_domain=ControlDomain.EVIDENCE_COMPLETENESS,
            severity=ControlSeverity.HIGH,
            applies_to=(ComplianceEntityType.EVIDENCE_PACK,),
            evidence_requirements=("control_results", "source_state"),
        ),
    )
